version: '3'

services:
  scrapy:
    build: .
    command: bash -c "rm -f tracks.csv && scrapy crawl squeeze-splash -L INFO -o 'scrapes/%(time)s.csv' -a target_count=${TARGET_COUNT}"
    volumes:
      - .:/app
    depends_on:
      - splash
    environment:
      SPLASH_URL: "http://splash:8050"

  splash:
    command: ["--max-timeout", "600"]
    image: scrapinghub/splash:3.3
    ports:
      - "8050:8050"
